### PR TITLE
Update chat links

### PR DESCRIPTION
**Pull request by swedneck**

### CODE REVIEW

**Comment by AquiGorka** [comment]
@swedneck can you let me know if these links are the correct ones instead of the ones currently at the README?

**Comment by swedneck** [comment]
the links in this PR are effectively the same as those currently in the README, however it might be better to use these direct links partly for transparency and partly so we don't have to rely on our server to redirect people.

**Comment by AquiGorka** [comment]
@swedneck ok, let's use this links then. I see there are conflicts with the renaming change, if you don't mind fixing those and afetr you've done that there's no need for another review on my part so you can go ahead and merge.

**Comment by swedneck** [comment]
@AquiGorka merged

**Pull request merged**
